### ISSUE TITLE
分页加载的时候，这个loading状态在那里设置啊

### ISSUE THREAD

**Issue by myDonghao** [moliya/KFBlankSlate#1]
只有加载第一页的时候显示？那下拉刷新的时候还需要显示吗

**Comment by moliya** [comment]
Loading状态只在列表为空的时候展示，所以如果列表已加载了第一页数据，就不会显示

**Comment by myDonghao** [comment]
哦哦，谢谢大大，我正读这个库，写的很好！
有没有考虑为view也搞一个，vc在加载数据的时候应该也会遇到这样的需求

**Comment by moliya** [comment]
因为这个库是基于[DZNEmptyDataSet](https://github.com/dzenbot/DZNEmptyDataSet)实现的，所以只支持UIScrollView及其子类。要想添加到UIView上，只能自行实现了。
